// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(BizyPopDbContext))]
    [Migration("20260304175512_AddCustomerEntity")]
    partial class AddCustomerEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Business", b =>
                {
                    b.Property<long>("BusinessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("BusinessID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("BusinessId"));

                    b.Property<string>("BusinessEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("BusinessEmail");

                    b.Property<string>("BusinessImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("BusinessImageUrl");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("BusinessName");

                    b.Property<string>("BusinessPhone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("BusinessPhone");

                    b.Property<string>("BusinessURL")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("BusinessURL");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("CategoryID");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("City");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Country");

                    b.Property<short>("CountryCode")
                        .HasColumnType("smallint")
                        .HasColumnName("CountryCode");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedOn");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("Latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("Longitude");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("State");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("StreetAddress");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ZipCode");

                    b.HasKey("BusinessId");

                    b.HasIndex("BusinessEmail")
                        .IsUnique()
                        .HasDatabaseName("IX_Business_BusinessEmail");

                    b.HasIndex("BusinessName")
                        .HasDatabaseName("IX_Business_BusinessName");

                    b.HasIndex("BusinessPhone")
                        .HasDatabaseName("IX_Business_BusinessPhone");

                    b.HasIndex("CategoryId", "CreatedOn")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Business_CategoryID_CreatedOn");

                    b.ToTable("B01_Business_Profile", (string)null);
                });

            modelBuilder.Entity("Domain.BusinessCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("CategoryID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CategoryName");

                    b.Property<string>("CategorySlug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CategorySlug");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedOn");

                    b.Property<short>("DisplayColumn")
                        .HasColumnType("smallint")
                        .HasColumnName("DisplayColumn");

                    b.Property<short>("DisplayOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("DisplayOrder");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IsActive");

                    b.HasKey("CategoryId");

                    b.HasIndex("CategoryName")
                        .IsUnique()
                        .HasDatabaseName("IX_BusinessCategory_CategoryName");

                    b.HasIndex("IsActive", "DisplayColumn", "DisplayOrder")
                        .HasDatabaseName("IX_BusinessCategory_IsActive_DisplayColumn_DisplayOrder");

                    b.ToTable("B04_Business_Category", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Restaurant & Bar",
                            CategorySlug = "restaurant-bar",
                            CreatedOn = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayColumn = (short)1,
                            DisplayOrder = (short)1,
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Desert and Drinks",
                            CategorySlug = "desert-and-drinks",
                            CreatedOn = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayColumn = (short)1,
                            DisplayOrder = (short)2,
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Entertainment",
                            CategorySlug = "entertainment",
                            CreatedOn = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayColumn = (short)1,
                            DisplayOrder = (short)3,
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Beauty and Health",
                            CategorySlug = "beauty-and-health",
                            CreatedOn = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayColumn = (short)1,
                            DisplayOrder = (short)4,
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Hotel & Travel",
                            CategorySlug = "hotel-travel",
                            CreatedOn = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayColumn = (short)1,
                            DisplayOrder = (short)5,
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "For Kids",
                            CategorySlug = "for-kids",
                            CreatedOn = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayColumn = (short)1,
                            DisplayOrder = (short)6,
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "For Pets",
                            CategorySlug = "for-pets",
                            CreatedOn = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayColumn = (short)1,
                            DisplayOrder = (short)7,
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Automotive Services",
                            CategorySlug = "automotive-services",
                            CreatedOn = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayColumn = (short)2,
                            DisplayOrder = (short)1,
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Cleaning",
                            CategorySlug = "cleaning",
                            CreatedOn = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayColumn = (short)2,
                            DisplayOrder = (short)2,
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Home Services",
                            CategorySlug = "home-services",
                            CreatedOn = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayColumn = (short)2,
                            DisplayOrder = (short)3,
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "Gym & Fitness",
                            CategorySlug = "gym-fitness",
                            CreatedOn = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayColumn = (short)2,
                            DisplayOrder = (short)4,
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "Real Estate",
                            CategorySlug = "real-estate",
                            CreatedOn = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayColumn = (short)2,
                            DisplayOrder = (short)5,
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 13,
                            CategoryName = "Legal",
                            CategorySlug = "legal",
                            CreatedOn = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayColumn = (short)2,
                            DisplayOrder = (short)6,
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 14,
                            CategoryName = "Medical Services",
                            CategorySlug = "medical-services",
                            CreatedOn = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayColumn = (short)2,
                            DisplayOrder = (short)7,
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 15,
                            CategoryName = "Professional Services (other)",
                            CategorySlug = "professional-services-other",
                            CreatedOn = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayColumn = (short)2,
                            DisplayOrder = (short)8,
                            IsActive = true
                        });
                });

            modelBuilder.Entity("Domain.BusinessUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("UserID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<long>("BusinessId")
                        .HasColumnType("bigint")
                        .HasColumnName("BusinessID");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedOn");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("FirstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("LastName");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("RefreshToken");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("RefreshTokenExpiryTime");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TimeZone");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId")
                        .HasDatabaseName("IX_BusinessUser_BusinessID");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_BusinessUser_Email");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("B02_Business_User", (string)null);
                });

            modelBuilder.Entity("Domain.Coupon", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("CouponID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BusinessId")
                        .HasColumnType("bigint")
                        .HasColumnName("BusinessID");

                    b.Property<int>("CouponTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("CouponTypeID");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedOn");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("EndDateTime");

                    b.Property<DateTime>("ExpirationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ExpirationTime");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean")
                        .HasColumnName("IsFeatured");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("Picture");

                    b.Property<string>("QRCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("QRCode");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("StartDateTime");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Title");

                    b.Property<string>("TrackCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TrackCode");

                    b.HasKey("Id");

                    b.HasIndex("CouponTypeId")
                        .HasDatabaseName("IX_Coupon_CouponTypeID");

                    b.HasIndex("QRCode")
                        .IsUnique()
                        .HasDatabaseName("IX_Coupon_QRCode");

                    b.HasIndex("TrackCode")
                        .IsUnique()
                        .HasDatabaseName("IX_Coupon_TrackCode");

                    b.HasIndex("BusinessId", "CreatedOn")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Coupon_BusinessID_CreatedOn");

                    b.HasIndex("IsActive", "IsFeatured")
                        .HasDatabaseName("IX_Coupon_IsActive_IsFeatured");

                    b.HasIndex("StartDateTime", "EndDateTime")
                        .HasDatabaseName("IX_Coupon_DateRange");

                    b.ToTable("B04_Coupon", (string)null);
                });

            modelBuilder.Entity("Domain.CouponType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("CouponTypeID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedOn");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IsActive");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasColumnType("character(1)")
                        .HasColumnName("TypeCode");

                    b.Property<string>("TypeDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TypeDescription");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_CouponType_IsActive");

                    b.HasIndex("TypeCode")
                        .IsUnique()
                        .HasDatabaseName("IX_CouponType_TypeCode");

                    b.ToTable("B05_Coupon_Type", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            TypeCode = "B",
                            TypeDescription = "BizyPop Dollars"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            TypeCode = "C",
                            TypeDescription = "Coupon"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            TypeCode = "S",
                            TypeDescription = "Stamp"
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            TypeCode = "M",
                            TypeDescription = "Promotions"
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            TypeCode = "G",
                            TypeDescription = "Gift Card"
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            TypeCode = "R",
                            TypeDescription = "Store Credit"
                        },
                        new
                        {
                            Id = 7,
                            CreatedOn = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            TypeCode = "P",
                            TypeDescription = "Store Point"
                        },
                        new
                        {
                            Id = 8,
                            CreatedOn = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            TypeCode = "V",
                            TypeDescription = "VIP Access"
                        },
                        new
                        {
                            Id = 9,
                            CreatedOn = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            TypeCode = "I",
                            TypeDescription = "Check-In"
                        });
                });

            modelBuilder.Entity("Domain.Customer", b =>
                {
                    b.Property<long>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("CustomerID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CustomerId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("FirstName");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("LastName");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("PhoneNumber");

                    b.Property<string>("ProfilePhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("ProfilePhotoUrl");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("RefreshToken");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("RefreshTokenExpiryTime");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TimeZone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("CustomerId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Customer_CreatedAt");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_Customer_Email");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Customer_IsActive");

                    b.ToTable("C01_Customer", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<long>", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Business_Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Business_Roles_Claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Business_User_Claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("Business_User_Logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("Business_User_Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("Business_User_Tokens", (string)null);
                });

            modelBuilder.Entity("Domain.Business", b =>
                {
                    b.HasOne("Domain.BusinessCategory", "Category")
                        .WithMany("Businesses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.BusinessUser", b =>
                {
                    b.HasOne("Domain.Business", "Business")
                        .WithMany("BusinessUsers")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("Domain.Coupon", b =>
                {
                    b.HasOne("Domain.Business", "Business")
                        .WithMany("Coupons")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.CouponType", "CouponType")
                        .WithMany("Coupons")
                        .HasForeignKey("CouponTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("CouponType");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<long>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.HasOne("Domain.BusinessUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.HasOne("Domain.BusinessUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<long>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.BusinessUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.HasOne("Domain.BusinessUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Business", b =>
                {
                    b.Navigation("BusinessUsers");

                    b.Navigation("Coupons");
                });

            modelBuilder.Entity("Domain.BusinessCategory", b =>
                {
                    b.Navigation("Businesses");
                });

            modelBuilder.Entity("Domain.CouponType", b =>
                {
                    b.Navigation("Coupons");
                });
#pragma warning restore 612, 618
        }
    }
}
