// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(BizyPopDbContext))]
    [Migration("20260310182948_Add new tables for the address")]
    partial class Addnewtablesfortheaddress
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Business", b =>
                {
                    b.Property<long>("BusinessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("BusinessID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("BusinessId"));

                    b.Property<string>("BusinessEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("BusinessEmail");

                    b.Property<string>("BusinessImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("BusinessImageUrl");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("BusinessName");

                    b.Property<string>("BusinessPhone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("BusinessPhone");

                    b.Property<string>("BusinessURL")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("BusinessURL");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("CategoryID");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Country");

                    b.Property<short>("CountryCode")
                        .HasColumnType("smallint")
                        .HasColumnName("CountryCode");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedOn");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("Latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("Longitude");

                    b.Property<long>("StateCityId")
                        .HasColumnType("bigint")
                        .HasColumnName("State_City_ID");

                    b.Property<long>("StateCityZipId")
                        .HasColumnType("bigint")
                        .HasColumnName("State_City_Zip_ID");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("StreetAddress");

                    b.HasKey("BusinessId");

                    b.HasIndex("BusinessEmail")
                        .IsUnique()
                        .HasDatabaseName("IX_Business_BusinessEmail");

                    b.HasIndex("BusinessName")
                        .HasDatabaseName("IX_Business_BusinessName");

                    b.HasIndex("BusinessPhone")
                        .HasDatabaseName("IX_Business_BusinessPhone");

                    b.HasIndex("StateCityId")
                        .HasDatabaseName("IX_Business_StateCityID");

                    b.HasIndex("StateCityZipId")
                        .HasDatabaseName("IX_Business_StateCityZipID");

                    b.HasIndex("CategoryId", "CreatedOn")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Business_CategoryID_CreatedOn");

                    b.ToTable("B01_Business_Profile", (string)null);
                });

            modelBuilder.Entity("Domain.BusinessCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("CategoryID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CategoryName");

                    b.Property<string>("CategorySlug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CategorySlug");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedOn");

                    b.Property<short>("DisplayColumn")
                        .HasColumnType("smallint")
                        .HasColumnName("DisplayColumn");

                    b.Property<short>("DisplayOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("DisplayOrder");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IsActive");

                    b.HasKey("CategoryId");

                    b.HasIndex("CategoryName")
                        .IsUnique()
                        .HasDatabaseName("IX_BusinessCategory_CategoryName");

                    b.HasIndex("IsActive", "DisplayColumn", "DisplayOrder")
                        .HasDatabaseName("IX_BusinessCategory_IsActive_DisplayColumn_DisplayOrder");

                    b.ToTable("B04_Business_Category", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Restaurant & Bar",
                            CategorySlug = "restaurant-bar",
                            CreatedOn = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayColumn = (short)1,
                            DisplayOrder = (short)1,
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Desert and Drinks",
                            CategorySlug = "desert-and-drinks",
                            CreatedOn = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayColumn = (short)1,
                            DisplayOrder = (short)2,
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Entertainment",
                            CategorySlug = "entertainment",
                            CreatedOn = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayColumn = (short)1,
                            DisplayOrder = (short)3,
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Beauty and Health",
                            CategorySlug = "beauty-and-health",
                            CreatedOn = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayColumn = (short)1,
                            DisplayOrder = (short)4,
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Hotel & Travel",
                            CategorySlug = "hotel-travel",
                            CreatedOn = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayColumn = (short)1,
                            DisplayOrder = (short)5,
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "For Kids",
                            CategorySlug = "for-kids",
                            CreatedOn = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayColumn = (short)1,
                            DisplayOrder = (short)6,
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "For Pets",
                            CategorySlug = "for-pets",
                            CreatedOn = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayColumn = (short)1,
                            DisplayOrder = (short)7,
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Automotive Services",
                            CategorySlug = "automotive-services",
                            CreatedOn = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayColumn = (short)2,
                            DisplayOrder = (short)1,
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Cleaning",
                            CategorySlug = "cleaning",
                            CreatedOn = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayColumn = (short)2,
                            DisplayOrder = (short)2,
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Home Services",
                            CategorySlug = "home-services",
                            CreatedOn = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayColumn = (short)2,
                            DisplayOrder = (short)3,
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "Gym & Fitness",
                            CategorySlug = "gym-fitness",
                            CreatedOn = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayColumn = (short)2,
                            DisplayOrder = (short)4,
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "Real Estate",
                            CategorySlug = "real-estate",
                            CreatedOn = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayColumn = (short)2,
                            DisplayOrder = (short)5,
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 13,
                            CategoryName = "Legal",
                            CategorySlug = "legal",
                            CreatedOn = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayColumn = (short)2,
                            DisplayOrder = (short)6,
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 14,
                            CategoryName = "Medical Services",
                            CategorySlug = "medical-services",
                            CreatedOn = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayColumn = (short)2,
                            DisplayOrder = (short)7,
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 15,
                            CategoryName = "Professional Services (other)",
                            CategorySlug = "professional-services-other",
                            CreatedOn = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayColumn = (short)2,
                            DisplayOrder = (short)8,
                            IsActive = true
                        });
                });

            modelBuilder.Entity("Domain.BusinessUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("UserID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<long>("BusinessId")
                        .HasColumnType("bigint")
                        .HasColumnName("BusinessID");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedOn");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("FirstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("LastName");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("RefreshToken");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("RefreshTokenExpiryTime");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TimeZone");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId")
                        .HasDatabaseName("IX_BusinessUser_BusinessID");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_BusinessUser_Email");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("B02_Business_User", (string)null);
                });

            modelBuilder.Entity("Domain.Coupon", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("CouponID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BusinessId")
                        .HasColumnType("bigint")
                        .HasColumnName("BusinessID");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedOn");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("EndDateTime");

                    b.Property<DateTime>("ExpirationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ExpirationTime");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean")
                        .HasColumnName("IsFeatured");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("Picture");

                    b.Property<string>("QRCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("QRCode");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("StartDateTime");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Title");

                    b.Property<string>("TrackCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TrackCode");

                    b.HasKey("Id");

                    b.HasIndex("QRCode")
                        .IsUnique()
                        .HasDatabaseName("IX_Coupon_QRCode");

                    b.HasIndex("TrackCode")
                        .IsUnique()
                        .HasDatabaseName("IX_Coupon_TrackCode");

                    b.HasIndex("BusinessId", "CreatedOn")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Coupon_BusinessID_CreatedOn");

                    b.HasIndex("IsActive", "IsFeatured")
                        .HasDatabaseName("IX_Coupon_IsActive_IsFeatured");

                    b.HasIndex("StartDateTime", "EndDateTime")
                        .HasDatabaseName("IX_Coupon_DateRange");

                    b.ToTable("10A_Coupon_BizDef", (string)null);
                });

            modelBuilder.Entity("Domain.Customer", b =>
                {
                    b.Property<long>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("CustomerID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CustomerId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("FirstName");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("LastName");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("ProfilePhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("ProfilePhotoUrl");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("RefreshToken");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("RefreshTokenExpiryTime");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TimeZone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("CustomerId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Customer_CreatedAt");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_Customer_Email");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Customer_IsActive");

                    b.ToTable("C01_Customer", (string)null);
                });

            modelBuilder.Entity("Domain.CustomerCoupon", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CashierNote")
                        .HasColumnType("text")
                        .HasColumnName("CashierNote");

                    b.Property<long>("CouponId")
                        .HasColumnType("bigint")
                        .HasColumnName("CouponID");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Created");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserID");

                    b.Property<DateTime?>("DateRedeemed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DateRedeemed");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastUpdated");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("Status");

                    b.Property<string>("StatusAdminNote")
                        .HasColumnType("text")
                        .HasColumnName("StatusAdminNote");

                    b.Property<DateTime>("StatusDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("StatusDate");

                    b.Property<string>("StatusUserNote")
                        .HasColumnType("text")
                        .HasColumnName("StatusUserNote");

                    b.HasKey("Id");

                    b.HasIndex("CouponId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_CouponUserEnt_Status");

                    b.HasIndex("CustomerId", "CouponId")
                        .IsUnique()
                        .HasDatabaseName("UX_CouponUserEnt_UserID_CouponID");

                    b.ToTable("10B_CouponUserEnt", (string)null);
                });

            modelBuilder.Entity("Domain.GeoCity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("City");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("State");

                    b.Property<bool>("UserInput")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("UserInput");

                    b.HasKey("Id");

                    b.HasIndex("City", "State")
                        .IsUnique()
                        .HasDatabaseName("IX_L50_City_State");

                    b.ToTable("L50_Geo_Cities", (string)null);
                });

            modelBuilder.Entity("Domain.GeoZipCode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("City");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("State");

                    b.Property<bool>("UserInput")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("UserInput");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ZipCode");

                    b.HasKey("Id");

                    b.HasIndex("City", "State", "ZipCode")
                        .IsUnique()
                        .HasDatabaseName("IX_L51_City_State_ZipCode");

                    b.ToTable("L51_Geo_ZipCodes", (string)null);
                });

            modelBuilder.Entity("Domain.IncentiveType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("CouponTypeID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedOn");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IsActive");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasColumnType("character(1)")
                        .HasColumnName("TypeCode");

                    b.Property<string>("TypeDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TypeDescription");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_CouponType_IsActive");

                    b.HasIndex("TypeCode")
                        .IsUnique()
                        .HasDatabaseName("IX_CouponType_TypeCode");

                    b.ToTable("B05_Coupon_Type", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            TypeCode = "B",
                            TypeDescription = "BizyPop Dollars"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            TypeCode = "C",
                            TypeDescription = "Coupon"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            TypeCode = "S",
                            TypeDescription = "Stamp"
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            TypeCode = "M",
                            TypeDescription = "Promotions"
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            TypeCode = "G",
                            TypeDescription = "Gift Card"
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            TypeCode = "R",
                            TypeDescription = "Store Credit"
                        },
                        new
                        {
                            Id = 7,
                            CreatedOn = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            TypeCode = "P",
                            TypeDescription = "Store Point"
                        },
                        new
                        {
                            Id = 8,
                            CreatedOn = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            TypeCode = "V",
                            TypeDescription = "VIP Access"
                        },
                        new
                        {
                            Id = 9,
                            CreatedOn = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            TypeCode = "I",
                            TypeDescription = "Check-In"
                        });
                });

            modelBuilder.Entity("Domain.State", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("text")
                        .HasColumnName("Code");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedOn");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<string>("Region")
                        .HasColumnType("text")
                        .HasColumnName("Region");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_L52_Code");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_L52_IsActive");

                    b.ToTable("L52_Geo_States", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "AL",
                            CreatedOn = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Alabama",
                            Region = "South"
                        },
                        new
                        {
                            Id = 2L,
                            Code = "AK",
                            CreatedOn = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Alaska",
                            Region = "West"
                        },
                        new
                        {
                            Id = 3L,
                            Code = "AZ",
                            CreatedOn = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Arizona",
                            Region = "West"
                        },
                        new
                        {
                            Id = 4L,
                            Code = "AR",
                            CreatedOn = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Arkansas",
                            Region = "South"
                        },
                        new
                        {
                            Id = 5L,
                            Code = "CA",
                            CreatedOn = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "California",
                            Region = "West"
                        },
                        new
                        {
                            Id = 6L,
                            Code = "CO",
                            CreatedOn = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Colorado",
                            Region = "West"
                        },
                        new
                        {
                            Id = 7L,
                            Code = "CT",
                            CreatedOn = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Connecticut",
                            Region = "Northeast"
                        },
                        new
                        {
                            Id = 8L,
                            Code = "DE",
                            CreatedOn = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Delaware",
                            Region = "South"
                        },
                        new
                        {
                            Id = 9L,
                            Code = "FL",
                            CreatedOn = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Florida",
                            Region = "South"
                        },
                        new
                        {
                            Id = 10L,
                            Code = "GA",
                            CreatedOn = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Georgia",
                            Region = "South"
                        },
                        new
                        {
                            Id = 11L,
                            Code = "HI",
                            CreatedOn = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Hawaii",
                            Region = "West"
                        },
                        new
                        {
                            Id = 12L,
                            Code = "ID",
                            CreatedOn = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Idaho",
                            Region = "West"
                        },
                        new
                        {
                            Id = 13L,
                            Code = "IL",
                            CreatedOn = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Illinois",
                            Region = "Midwest"
                        },
                        new
                        {
                            Id = 14L,
                            Code = "IN",
                            CreatedOn = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Indiana",
                            Region = "Midwest"
                        },
                        new
                        {
                            Id = 15L,
                            Code = "IA",
                            CreatedOn = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Iowa",
                            Region = "Midwest"
                        },
                        new
                        {
                            Id = 16L,
                            Code = "KS",
                            CreatedOn = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Kansas",
                            Region = "Midwest"
                        },
                        new
                        {
                            Id = 17L,
                            Code = "KY",
                            CreatedOn = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Kentucky",
                            Region = "South"
                        },
                        new
                        {
                            Id = 18L,
                            Code = "LA",
                            CreatedOn = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Louisiana",
                            Region = "South"
                        },
                        new
                        {
                            Id = 19L,
                            Code = "ME",
                            CreatedOn = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Maine",
                            Region = "Northeast"
                        },
                        new
                        {
                            Id = 20L,
                            Code = "MD",
                            CreatedOn = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Maryland",
                            Region = "South"
                        },
                        new
                        {
                            Id = 21L,
                            Code = "MA",
                            CreatedOn = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Massachusetts",
                            Region = "Northeast"
                        },
                        new
                        {
                            Id = 22L,
                            Code = "MI",
                            CreatedOn = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Michigan",
                            Region = "Midwest"
                        },
                        new
                        {
                            Id = 23L,
                            Code = "MN",
                            CreatedOn = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Minnesota",
                            Region = "Midwest"
                        },
                        new
                        {
                            Id = 24L,
                            Code = "MS",
                            CreatedOn = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Mississippi",
                            Region = "South"
                        },
                        new
                        {
                            Id = 25L,
                            Code = "MO",
                            CreatedOn = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Missouri",
                            Region = "Midwest"
                        },
                        new
                        {
                            Id = 26L,
                            Code = "MT",
                            CreatedOn = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Montana",
                            Region = "West"
                        },
                        new
                        {
                            Id = 27L,
                            Code = "NE",
                            CreatedOn = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Nebraska",
                            Region = "Midwest"
                        },
                        new
                        {
                            Id = 28L,
                            Code = "NV",
                            CreatedOn = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Nevada",
                            Region = "West"
                        },
                        new
                        {
                            Id = 29L,
                            Code = "NH",
                            CreatedOn = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "New Hampshire",
                            Region = "Northeast"
                        },
                        new
                        {
                            Id = 30L,
                            Code = "NJ",
                            CreatedOn = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "New Jersey",
                            Region = "Northeast"
                        },
                        new
                        {
                            Id = 31L,
                            Code = "NM",
                            CreatedOn = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "New Mexico",
                            Region = "West"
                        },
                        new
                        {
                            Id = 32L,
                            Code = "NY",
                            CreatedOn = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "New York",
                            Region = "Northeast"
                        },
                        new
                        {
                            Id = 33L,
                            Code = "NC",
                            CreatedOn = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "North Carolina",
                            Region = "South"
                        },
                        new
                        {
                            Id = 34L,
                            Code = "ND",
                            CreatedOn = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "North Dakota",
                            Region = "Midwest"
                        },
                        new
                        {
                            Id = 35L,
                            Code = "OH",
                            CreatedOn = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Ohio",
                            Region = "Midwest"
                        },
                        new
                        {
                            Id = 36L,
                            Code = "OK",
                            CreatedOn = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Oklahoma",
                            Region = "South"
                        },
                        new
                        {
                            Id = 37L,
                            Code = "OR",
                            CreatedOn = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Oregon",
                            Region = "West"
                        },
                        new
                        {
                            Id = 38L,
                            Code = "PA",
                            CreatedOn = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Pennsylvania",
                            Region = "Northeast"
                        },
                        new
                        {
                            Id = 39L,
                            Code = "RI",
                            CreatedOn = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Rhode Island",
                            Region = "Northeast"
                        },
                        new
                        {
                            Id = 40L,
                            Code = "SC",
                            CreatedOn = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "South Carolina",
                            Region = "South"
                        },
                        new
                        {
                            Id = 41L,
                            Code = "SD",
                            CreatedOn = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "South Dakota",
                            Region = "Midwest"
                        },
                        new
                        {
                            Id = 42L,
                            Code = "TN",
                            CreatedOn = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Tennessee",
                            Region = "South"
                        },
                        new
                        {
                            Id = 43L,
                            Code = "TX",
                            CreatedOn = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Texas",
                            Region = "South"
                        },
                        new
                        {
                            Id = 44L,
                            Code = "UT",
                            CreatedOn = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Utah",
                            Region = "West"
                        },
                        new
                        {
                            Id = 45L,
                            Code = "VT",
                            CreatedOn = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Vermont",
                            Region = "Northeast"
                        },
                        new
                        {
                            Id = 46L,
                            Code = "VA",
                            CreatedOn = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Virginia",
                            Region = "South"
                        },
                        new
                        {
                            Id = 47L,
                            Code = "WA",
                            CreatedOn = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Washington",
                            Region = "West"
                        },
                        new
                        {
                            Id = 48L,
                            Code = "WV",
                            CreatedOn = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "West Virginia",
                            Region = "South"
                        },
                        new
                        {
                            Id = 49L,
                            Code = "WI",
                            CreatedOn = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Wisconsin",
                            Region = "Midwest"
                        },
                        new
                        {
                            Id = 50L,
                            Code = "WY",
                            CreatedOn = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Wyoming",
                            Region = "West"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<long>", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Business_Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Business_Roles_Claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Business_User_Claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("Business_User_Logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("Business_User_Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("Business_User_Tokens", (string)null);
                });

            modelBuilder.Entity("Domain.Business", b =>
                {
                    b.HasOne("Domain.BusinessCategory", "Category")
                        .WithMany("Businesses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.GeoCity", "GeoCity")
                        .WithMany("Businesses")
                        .HasForeignKey("StateCityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.GeoZipCode", "GeoZipCode")
                        .WithMany("Businesses")
                        .HasForeignKey("StateCityZipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("GeoCity");

                    b.Navigation("GeoZipCode");
                });

            modelBuilder.Entity("Domain.BusinessUser", b =>
                {
                    b.HasOne("Domain.Business", "Business")
                        .WithMany("BusinessUsers")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("Domain.Coupon", b =>
                {
                    b.HasOne("Domain.Business", "Business")
                        .WithMany("Coupons")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("Domain.CustomerCoupon", b =>
                {
                    b.HasOne("Domain.Coupon", "Coupon")
                        .WithMany("CustomerCoupons")
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Customer", "Customer")
                        .WithMany("CustomerCoupons")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coupon");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<long>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.HasOne("Domain.BusinessUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.HasOne("Domain.BusinessUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<long>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.BusinessUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.HasOne("Domain.BusinessUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Business", b =>
                {
                    b.Navigation("BusinessUsers");

                    b.Navigation("Coupons");
                });

            modelBuilder.Entity("Domain.BusinessCategory", b =>
                {
                    b.Navigation("Businesses");
                });

            modelBuilder.Entity("Domain.Coupon", b =>
                {
                    b.Navigation("CustomerCoupons");
                });

            modelBuilder.Entity("Domain.Customer", b =>
                {
                    b.Navigation("CustomerCoupons");
                });

            modelBuilder.Entity("Domain.GeoCity", b =>
                {
                    b.Navigation("Businesses");
                });

            modelBuilder.Entity("Domain.GeoZipCode", b =>
                {
                    b.Navigation("Businesses");
                });
#pragma warning restore 612, 618
        }
    }
}
