<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IncludeMigrationsInBuild>false</IncludeMigrationsInBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.3" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\Common.csproj" />
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(IncludeMigrationsInBuild)' != 'true'">
    <Compile Remove="Migrations\**\*.cs" />
    <None Include="Migrations\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Migrations\20260330221815_AddIncentiveUpdatesAndLookupTables.cs" />
    <None Remove="Migrations\20260330221815_AddIncentiveUpdatesAndLookupTables.Designer.cs" />
    <None Remove="Migrations\BizyPopDbContextModelSnapshot.cs" />
    <None Remove="Migrations\LoggingDb\20260331231811_AppendingLoggingDbForSystemLogs.cs" />
    <None Remove="Migrations\LoggingDb\20260331231811_AppendingLoggingDbForSystemLogs.Designer.cs" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Migrations\20260330221815_AddIncentiveUpdatesAndLookupTables.cs" />
    <Compile Include="Migrations\20260330221815_AddIncentiveUpdatesAndLookupTables.Designer.cs" />
    <Compile Include="Migrations\BizyPopDbContextModelSnapshot.cs" />
    <Compile Include="Migrations\LoggingDb\20260331231811_AppendingLoggingDbForSystemLogs.cs" />
    <Compile Include="Migrations\LoggingDb\20260331231811_AppendingLoggingDbForSystemLogs.Designer.cs" />
  </ItemGroup>

</Project>
