// <auto-generated />
using System;
using System.Text.Json;
using Infrastructure.Logging;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations.LoggingDb
{
    [DbContext(typeof(LoggingDbContext))]
    [Migration("20260331231811_AppendingLoggingDbForSystemLogs")]
    partial class AppendingLoggingDbForSystemLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Logging.AppLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("Category");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text")
                        .HasColumnName("CorrelationId");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<JsonDocument>("Data")
                        .HasColumnType("jsonb")
                        .HasColumnName("Data");

                    b.Property<string>("EventName")
                        .HasColumnType("text")
                        .HasColumnName("EventName");

                    b.Property<string>("ExceptionMessage")
                        .HasColumnType("text")
                        .HasColumnName("ExceptionMessage");

                    b.Property<string>("ExceptionType")
                        .HasColumnType("text")
                        .HasColumnName("ExceptionType");

                    b.Property<string>("HttpMethod")
                        .HasColumnType("text")
                        .HasColumnName("HttpMethod");

                    b.Property<short>("Level")
                        .HasColumnType("smallint")
                        .HasColumnName("Level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Message");

                    b.Property<JsonDocument>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("Metadata");

                    b.Property<string>("RequestPath")
                        .HasColumnType("text")
                        .HasColumnName("RequestPath");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text")
                        .HasColumnName("StackTrace");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_L01_AppLog_CorrelationId");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_L01_AppLog_CreatedAtUtc");

                    b.HasIndex("Level", "CreatedAtUtc")
                        .HasDatabaseName("IX_L01_AppLog_Level_CreatedAtUtc");

                    b.ToTable("L01_AppLog", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
